version: "3"

services:
  app:
    build: .
    container_name: tereasticks.ru # меняем на имя проекта
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tereasticks.ru,www.tereasticks.ru
      - LETSENCRYPT_HOST=tereasticks.ru,www.tereasticks.ru
      - LETSENCRYPT_EMAIL=parsh@gmail.com
      - REDIRECT_www.tereasticks.ru=tereasticks.ru
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/tereasticks.ru/.next:/app/.next

networks:
  web:
    external: true
