version: "3"

services:
  app:
    build: .
    container_name: tereasticks.ru # меняем на имя проекта
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tereasticks.ru # домен сайта
      - LETSENCRYPT_HOST=tereasticks.ru # домен для SSL
      - LETSENCRYPT_EMAIL=qwe@email.com
    networks:
      - web

networks:
  web:
    external: true
